name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

# some jobs are currently running multiple config builds on the same worktree.
# it might be better to issue these as separate jobs or as a config matrix.

# debug builds are currently not built to keep the turnaround time on PRs shorter.

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: make mingw-w64-x86_64-gcc
      - name: build
        shell: msys2 {0}
        run: |
          cd "${{ github.workspace }}"
          make -j4 platform=win config=player
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lutro-core
          path: lutro_libretro.dll
  build_windows_jit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: make mingw-w64-x86_64-gcc
      - name: build
        shell: msys2 {0}
        run: |
          cd "${{ github.workspace }}"
          make -j4 platform=win config=player WANT_JIT=1 
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lutro-core-jit
          path: lutro_libretro.dll
  build_linux_arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          git apply -v recalbox-unzip-path.patch
          make -j4 config=player WANT_JIT=1
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lutro-core-recallbox
          path: lutro_libretro.so
